name: anitemp
description: Record all warm-blood animal's body temperature
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons: ^1.0.4
  fluent_ui: ^3.12.0
  google_fonts: ^2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
