name: anitemp
description: Record all warm-blood animal's body temperature
publish_to: 'none'
version: 0.0.0-alpha+1
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^10.1.0
  # google_fonts: ^2.3.2
  provider: ^6.0.3
  hive: ^2.1.1
  hive_flutter: ^1.1.0
  sqflite: ^2.0.2+1
  sqflite_common_ffi: ^2.1.1
  sqlite3_flutter_libs: ^0.5.7
  path: ^1.8.1
  path_provider: ^2.0.10
  meta: ^1.7.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: a738913c8ce2c9f47515382d40827e794a334274
  flutter_localized_locales: ^2.0.3
  package_info_plus: ^1.4.2
  flutter_window_close: ^0.2.2
  quiver: ^3.1.0
  mime: ^1.0.2
  lzma: ^1.0.1
  collection: ^1.16.0
  csv: ^5.0.1
  pointycastle: ^3.6.0
  toggle_switch: ^2.0.1
  date_field: ^3.0.1
  intl: ^0.17.0
  flutter_native_splash: ^2.2.2
  crop_image: ^1.0.2
  image: ^3.2.0
  sn_progress_dialog: ^1.0.8
  remove_emoji: ^0.0.7
  file_picker: ^4.6.0
  image_picker: ^0.8.5+3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
flutter:
  uses-material-design: true
  generate: true
  assets:
    - logo/vector/icon.svg
  fonts:
    - family: Roboto
      fonts: 
        - asset: fonts/roboto/Roboto-Regular.ttf
        - asset: fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Noto Sans HK
      fonts: 
        - asset: fonts/noto_sans_hk/NotoSansHK-Regular.otf
        - asset: fonts/noto_sans_hk/NotoSansHK-Thin.otf
          weight: 100
        - asset: fonts/noto_sans_hk/NotoSansHK-Light.otf
          weight: 300
        - asset: fonts/noto_sans_hk/NotoSansHK-Medium.otf
          weight: 500
        - asset: fonts/noto_sans_hk/NotoSansHK-Bold.otf
          weight: 700
        - asset: fonts/noto_sans_hk/NotoSansHK-Black.otf
          weight: 900
    - family: Noto Sans JP
      fonts: 
        - asset: fonts/noto_sans_jp/NotoSansJP-Regular.otf
        - asset: fonts/noto_sans_jp/NotoSansJP-Thin.otf
          weight: 100
        - asset: fonts/noto_sans_jp/NotoSansJP-Light.otf
          weight: 300
        - asset: fonts/noto_sans_jp/NotoSansJP-Medium.otf
          weight: 500
        - asset: fonts/noto_sans_jp/NotoSansJP-Bold.otf
          weight: 700
        - asset: fonts/noto_sans_jp/NotoSansJP-Black.otf
          weight: 900
    - family: Noto Sans KR
      fonts: 
        - asset: fonts/noto_sans_kr/NotoSansKR-Regular.otf
        - asset: fonts/noto_sans_kr/NotoSansKR-Thin.otf
          weight: 100
        - asset: fonts/noto_sans_kr/NotoSansKR-Light.otf
          weight: 300
        - asset: fonts/noto_sans_kr/NotoSansKR-Medium.otf
          weight: 500
        - asset: fonts/noto_sans_kr/NotoSansKR-Bold.otf
          weight: 700
        - asset: fonts/noto_sans_kr/NotoSansKR-Black.otf
          weight: 900
    - family: Noto Sans TC
      fonts: 
        - asset: fonts/noto_sans_tc/NotoSansTC-Regular.otf
        - asset: fonts/noto_sans_tc/NotoSansTC-Thin.otf
          weight: 100
        - asset: fonts/noto_sans_tc/NotoSansTC-Light.otf
          weight: 300
        - asset: fonts/noto_sans_tc/NotoSansTC-Medium.otf
          weight: 500
        - asset: fonts/noto_sans_tc/NotoSansTC-Bold.otf
          weight: 700
        - asset: fonts/noto_sans_tc/NotoSansTC-Black.otf
          weight: 900
    - family: Noto Sans SC
      fonts: 
        - asset: fonts/noto_sans_sc/NotoSansSC-Regular.otf
        - asset: fonts/noto_sans_sc/NotoSansSC-Thin.otf
          weight: 100
        - asset: fonts/noto_sans_sc/NotoSansSC-Light.otf
          weight: 300
        - asset: fonts/noto_sans_sc/NotoSansSC-Medium.otf
          weight: 500
        - asset: fonts/noto_sans_sc/NotoSansSC-Bold.otf
          weight: 700
        - asset: fonts/noto_sans_sc/NotoSansSC-Black.otf
          weight: 900

