name: anitemp
description: Record all warm-blood animal's body temperature
publish_to: 'none'
version: 0.0.0-alpha+1
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons: ^1.0.4
  fluent_ui: ^3.12.0
  fluentui_icons: ^1.0.0
  fluentui_system_icons: ^1.1.168
  google_fonts: ^2.3.2
  units_converter: ^1.2.0
  provider: ^6.0.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  sqflite: ^2.0.2+1
  sqflite_common_ffi: ^2.1.1
  sqlite3_flutter_libs: ^0.5.7
  path: ^1.8.1
  path_provider: ^2.0.10
  meta: ^1.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  generate: true
