name: Anitemp data archive format test
on:
  push:
    branches:
      - main
    paths:
      - lib/archive/archivable.dart
      - lib/archive/codec.dart
      - test/data/atda/**.dart
      - .github/workflows/atda_test.yml
jobs:
  unittest:
    env:
      TEST_ATDA: "1"
    name: Unit test
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
          - macos-12
          - macos-10.15
          - windows-2019
          - ubuntu-22.04
        flutter-channel:
          - stable
          # - dev
          - beta
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Submodule init
        run: git submodule update --init --recursive
      - name: Setup Flutter action
        uses: subosito/flutter-action@v2.4.0
        with:
          channel: ${{ matrix.flutter-channel }}
      - name: Print version
        run: flutter --version
      - name: Get dependencies
        run: flutter pub get
      - name: Execute test
        run: flutter test test/data/atda/
